# Generated by Django 6.0.7 on 2026-09-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='about/profile/', verbose_name='عکس پروفایل')),
                ('headline', models.CharField(help_text='مثال: توسعه\u200cدهنده بک\u200cاند و مدیر لینوکس', max_length=200, verbose_name='عنوان کوتاه حرفه\u200cای')),
                ('bio_text', models.TextField(verbose_name='متن بیوگرافی')),
                ('location', models.CharField(max_length=100, verbose_name='محل زندگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل عمومی')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='about/resume/', verbose_name='فایل رزومه (PDF)')),
            ],
            options={
                'verbose_name': 'بیوگرافی',
                'verbose_name_plural': 'بیوگرافی',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام مهارت')),
                ('category', models.CharField(choices=[('backend', 'بک\u200cاند'), ('frontend', 'فرانت\u200cاند'), ('devops', 'دواپس'), ('tools', 'ابزارها')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('proficiency', models.PositiveSmallIntegerField(verbose_name='سطح تسلط (۰ تا ۱۰۰)')),
                ('icon', models.ImageField(upload_to='about/skills/', verbose_name='آیکون/لوگو')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['category', '-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('education', 'تحصیلی'), ('work', 'شغلی')], max_length=20, verbose_name='نوع سابقه')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('organization', models.CharField(max_length=150, verbose_name='سازمان/دانشگاه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, help_text='اگر همچنان ادامه دارد، خالی بگذارید', null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه',
                'verbose_name_plural': 'سوابق تحصیلی و شغلی',
                'ordering': ['-start_date'],
            },
        ),
    ]
